name: EPS + BVK Apartmani Checker

on:
  schedule:
    - cron: "0 */2 * * *"   # svaka 2 sata (UTC)
  workflow_dispatch: {}      # i dalje možeš ručno pokrenuti

jobs:
  run-checker-apartmani:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 cyrtranslit

      - name: Run EPS + BVK Apartmani checker
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EMAIL_TO:   ${{ secrets.EMAIL_TO_SANJA }}
        run: |
          python apartmani_checker.py
