name: Send Test Mail

on:
  workflow_dispatch:   # ručno pokretanje iz Actions taba

jobs:
  send-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Send test email
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EMAIL_TO:   ${{ secrets.EMAIL_TO }}
        run: |
          python - <<'EOF'
          import os, smtplib
          from email.mime.text import MIMEText

          smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
          smtp_port = int(os.getenv("SMTP_PORT", "587"))
          smtp_user = os.getenv("SMTP_USER")
          smtp_pass = os.getenv("SMTP_PASS")
          email_to = os.getenv("EMAIL_TO")

          msg = MIMEText("✅ Ovo je test poruka sa GitHub Actions!")
          msg["Subject"] = "📧 Test GitHub Actions Email"
          msg["From"] = smtp_user
          msg["To"] = email_to

          try:
              with smtplib.SMTP(smtp_host, smtp_port) as server:
                  server.starttls()
                  server.login(smtp_user, smtp_pass)
                  server.send_message(msg)
              print(f"📧 Test email uspešno poslat na {email_to}")
          except Exception as e:
              print(f"⚠️ Greška pri slanju email-a: {e}")
              raise
          EOF
