name: Test Python Script

on:
  workflow_dispatch:  # omogućava ručno pokretanje

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 cyrtranslit

      - name: Show current dir and files
        run: |
          echo "=== Current working directory ==="
          pwd
          echo "=== Repo structure ==="
          ls -R

      - name: Run EPS checker
        run: |
          python ElectricityRestrictionsByStreet.py
